name: 'sdk ci'

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Typecheck
        run: deno check src/index.ts --unstable-sloppy-imports

      - name: Lint
        run: deno lint --unstable-sloppy-imports

      - name: Publish Dry Run
        run: deno publish --dry-run --allow-dirty
